services:
  server:
    container_name: bun-api
    image: localhost:5000/bun-api
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    restart: unless-stopped
    ports:
      - "3030:3030"
