services:
  server:
    container_name: bun-api
    image: localhost:5000/bun-api
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    restart: unless-stopped
    ports:
      - "3030:3030"
  client:
    container_name: flexroster
    image: localhost:5000/flexroster
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
