version: "3.8"

services:
  server:
    image: docker.laurel.k12.mt.us/bun-api
    ports:
      - "3030:3030"
    deploy:
      replicas: 3 # You can adjust the number of replicas as needed
      restart_policy:
        condition: on-failure
    networks:
      - webnet

  client:
    image: docker.laurel.k12.mt.us/flexroster
    ports:
      - "3000:3000"
    deploy:
      replicas: 3 # Adjust based on your needs
      restart_policy:
        condition: on-failure
    networks:
      - webnet
    env_file:
      - .env

networks:
  webnet:
