services:
  server:
    container_name: bun-api
    image: ghcr.io/biohackerellie/flexserver:main
    restart: unless-stopped
    ports:
      - "3030:3030"
    env_file:
      - .env

  client:
    container_name: flexroster
    image: ghcr.io/biohackerellie/flexclient:main
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
