azure_ad_client_id: 00000000-0000-0000-0000-000000000000
azure_ad_client_secret: your-azure-ad-client-secret
azure_ad_tenant_id: 00000000-0000-0000-0000-000000000000
azure_helpdesk_group: 00000000-0000-0000-0000-000000000000
azure_otherusers_group: 00000000-0000-0000-0000-000000000000
azure_student_group: 00000000-0000-0000-0000-000000000000
azure_teacher_group: 00000000-0000-0000-0000-000000000000
pgport: "5432"
pguser: postgres
pgpassword: postgres
pgdatabase: postgres
pghost: localhost
email_api: https://api.example.com/email
email_api_key: your-email-api-key
oneroster_appname: example_appname
oneroster_base_url: https://example.com/api/oneroster/v1p2/ims/oneroster
oneroster_client_id: your-oneroster-client-id
oneroster_client_secret: your-oneroster-client-secret
redis_host: sample.redis.host
redis_port: "6379"
semester_class_name: Sample-Semester
server_host: http://sample.server.host
server_port: "3030"
source_id: 00000000-0000-0000-0000-000000000000
tech_department_emails:
  - example_email@example.com
xsrf_token: your-xsrf-token
excluded_teachers:
  - Teacher One
  - Teacher Two
preferred_names:
  - givenname: Firstname Lastname
    preferredname: Preferred Name
  - givenname: Another Name
    preferredname: Preferred Name
secretaries:
  - secretary1@example.com
  - secretary2@example.com
  - secretary3@example.com
