packages:
  - "packages/*"
  - "apps/*"
  - "tooling/*"

catalog:
  eslint: ^9.7.0
  prettier: ^3.3.3
  typescript: ^5.5.3
  zod: ^3.23.8

catalogs:
  react19:
    react: ^19.0.0-rc-fb9a90fa48-20240614
    react-dom: ^19.0.0-rc-fb9a90fa48-20240614
    "@types/react": "npm:types-react@rc"
    "@types/react-dom": "npm:types-react-dom@rc"
