packages:
  - "packages/*"
  - "apps/*"
  - "tooling/*"

catalog:
  eslint: ^9.9.0
  prettier: ^3.3.3
  typescript: ^5.6.0
  tailwindcss: ^3.4.13
  zod: ^3.23.8

catalogs:
  react19:
    react: ^19.0.0-rc-cd22717c-20241013
    react-dom: ^19.0.0-rc-cd22717c-20241013
    "@types/react": "npm:types-react@19.0.0-rc.1"
    "@types/react-dom": "npm:types-react-dom@19.0.0-rc.1"
