//This File is automatically generated, do not edit

export const secretaries = [""];
export const preferredNames = [{ givenName: "", preferredName: "" }];
export const excludedTeachers = [""];
export const semesterClassName = "";
export const isRedisCluster: boolean = true;
