# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json

before:
  hooks:
    # - go mod download
    - go mod tidy

builds:
  - main: ./main.go
    id: flex
  - env:
      - CGO_ENABLED=0
    goos:
      - linux

    ldflags: -s -w -X main.Version=v{{ .Version }} -X main.CommitSHA={{ .Commit }} -X main.CommitDate={{ .CommitDate }}
release:
  prerelease: auto

universal_binaries:
  - replace: true

archives:
  - id: flexArch
    builds: [flex]
  - name_template: >-
      {{- .ProjectName }}_ {{- .Version }}_ {{- title .Os }}_ {{- if eq .Arch "amd64" }}x86_64 {{- else if eq .Arch "386" }}i386 {{- else }}{{ .Arch }}{{ end }} {{- if .Arm }}v{{ .Arm }}{{ end -}}
    wrap_in_directory: true
    allow_different_binary_count: true
    builds_info:
      group: root
      owner: root
