apiVersion: v1
kind: Service
metadata:
  name: flexroster-client
spec:
  type: NodePort
  selector:
    app: flexroster-client
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
      protocol: TCP
