apiVersion: v1
kind: Service
metadata:
  name: flexroster-server
spec:
  type: NodePort
  selector:
    app: flexroster-server
  ports:
    - port: 3030
      targetPort: 3030
      nodePort: 30030
      protocol: TCP
