version: "3"
services:
  postgresql:
    image: bitnami/postgresql
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - "pg_data:/bitnami/postgresql"
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
  pgbouncer:
    image: bitnami/pgbouncer
    restart: always
    ports:
      - "6543:6543"
    depends_on:
      - postgresql
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_PORT=5432
      - PGBOUNCER_LISTEN_PORT=6543
      - PGBOUNCER_MAX_CLIENT_CONN=200
      - PGBOUNCER_DEFAULT_POOL_SIZE=20
      - PGBOUNCER_ADMIN_USERS=postgres
      - PGBOUNCER_AUTH_TYPE=any
      - PGBOUNCER_MAX_DB_CONNECTIONS=50
volumes:
  pg_data:
    driver: local
