// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	UserId            string
	Type              string
	Provider          string
	ProviderAccountId string
	RefreshToken      pgtype.Text
	AccessToken       pgtype.Text
	ExpiresAt         pgtype.Int4
	TokenType         pgtype.Text
	Scope             pgtype.Text
	IDToken           pgtype.Text
	SessionState      pgtype.Text
}

type Availability struct {
	ID          string
	ClassroomId string
	Date        pgtype.Date
	Available   bool
	TeacherId   pgtype.Text
}

type Classroom struct {
	ID          string
	RoomNumber  string
	TeacherName string
	TeacherId   pgtype.Text
	Comment     pgtype.Text
	IsFlex      pgtype.Bool
}

type Config struct {
	Secretaries       []string
	PreferredNames    []byte
	ExcludedTeachers  []string
	SemesterClassName pgtype.Text
	IsRedisCluster    pgtype.Bool
	CreatedAt         pgtype.Timestamp
}

type Log struct {
	ID     string
	User   pgtype.Text
	Type   string
	Action string
}

type Request struct {
	ID                 int32
	StudentId          string
	StudentName        string
	NewTeacher         string
	NewTeacherName     string
	CurrentTeacher     string
	CurrentTeacherName string
	DateRequested      pgtype.Date
	Status             interface{}
	Arrived            pgtype.Bool
	Timestamp          string
}

type Session struct {
	SessionToken string
	UserId       string
	Expires      pgtype.Timestamp
}

type Student struct {
	StudentEmail string
	StudentName  string
	ClassroomId  string
	Status       interface{}
	ID           int32
}

type User struct {
	ID            string
	Name          pgtype.Text
	Email         string
	EmailVerified pgtype.Timestamp
	Image         pgtype.Text
	Role          string
}

type VerificationToken struct {
	Identifier string
	Token      string
	Expires    pgtype.Timestamp
}
