//This File is automatically generated, do not edit

export const secretaries = [
  "rachel_gappa@laurel.k12.mt.us",
  "marita_grammar@laurel.k12.mt.us",
  "brandi_fox@laurel.k12.mt.us",
  "hsmessage@laurel.k12.mt.us",
  "admin@laurel.k12.mt.us",
  "stacy_hall@laurel.k12.mt.us",
  "john_stilson@laurel.k12.mt.us",
];

export const preferredNames = [
  { givenName: "Carol Leinwand", preferredName: "Jeannie Leinwand" },
  { givenName: "Donna Kegel", preferredName: "Evawn Kegel" },
];

export const excludedTeachers = ["Brandi Fox,fox, Brandi"];

export const semesterClassName = "STEAM-B";

export const isRedisCluster: boolean = true;
