//This File is automatically generated, do not edit

export const secretaries = [
  "rachel_gappa@laurel.k12.mt.us",
  "marita_grammar@laurel.k12.mt.us",
  "brandi_fox@laurel.k12.mt.us",
  "hsmessage@laurel.k12.mt.us",
  "admin@laurel.k12.mt.us",
  "john_stilson@laurel.k12.mt.us",
];

export const preferredNames = [
  { givenName: "Donna Kegel", preferredName: "Evawn Kegel" },
];

export const excludedTeachers = [
  "Brandi Fox,Fox, Brandi",
  "me me me",
  "stop it",
];

export const semesterClassName = "STEAM-B";

export const isRedisCluster = true;
