version: '3'
services: 
  redis: 
    restart: always
    image: redis/redis-stack:latest
    container_name: redis
    ports: 
      - 6379:6379
    volumes: 
      - redisData:/usr/share/redis/data

volumes:
  redisData:
    driver: local