FROM pypy:latest

WORKDIR /usr/src/app

COPY app.py /usr/src/app/
COPY requirements.txt /usr/src/app/

RUN apt-get update
RUN apt-get install -y vim

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

RUN mkdir -p /usr/src/logs

EXPOSE 611

VOLUME ["/usr/src/app"]

ENTRYPOINT ["pypy3", "app.py"]
