export const greetings = [
  "What's Kickin",
  'Howdy Doody',
  'Greetings Earthling',
  "What's Crackalackin",
  "How's it Hanging",
  'Hey there, Space Cowboy',
  'Ahoy, Matey',
  'What in tarnation',
  'Bonjour',
  'Hellloooooooo',
  'Hey',
  'Hi',
  "What's Poppin",
  "Look who's here! It's",
  'Sup',
  "What's Poppin",
  'Yo Yo Yo',
] as const;
