# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/cli/main.go
    id: "cli"
    binary: flexroster
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - "386"
      - "arm"
    goarm:
    - "6"
    - "7"
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm

    ldflags: -s -w -X main.Version=v{{ .Version }} -X main.CommitSHA={{ .Commit }} -X main.CommitDate={{ .CommitDate }}
    no_unique_dist_dir: false

archives:
  - format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    files:
      - README*
      - LICENSE*
signs:
  - artifacts: checksum
    cmd: gpg
    args:
      - "--batch"
      - "-u"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
# winget:
#   name: "FlexRoster"
#   publisher: "Ellie Kerns"
#   short_description: "Self hosted school scheduling software"
#   license: "GNU GPL v3"
#   publisher_url: https://epklabs.com
#   publisher_support_url: "https://github.com/biohackerellie/FlexRoster/issues"
#   package_identifier: "biohackerellie.flexroster"

#   commit_author:
#     name: "Ellie Kerns"
#     email: "epkerns@gmail.com"
#   homepage: "https://epklabs.com"
#   copyright: "Ellie Kerns"
#   release_notes: "{{.Changelog}}"
#   tags:
#     - golang
#     - school
#     - scheduling
#     - software
#     - cli
#     - flexroster
