# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2
before:
  hooks:
    - go mod tidy
prepare:
  - |
    #!/bin/bash
    cp ./exampleConfig.yaml ./config.yaml
builds:
  - main: ./cmd/cli/main.go
    id: "cli"
    binary: flexroster
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm

    ldflags: -s -w -X main.Version=v{{ .Version }} -X main.CommitSHA={{ .Commit }} -X main.CommitDate={{ .CommitDate }}
    no_unique_dist_dir: false

archives:
  - format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    files:
      - config.yaml
signs:
  - artifacts: checksum
    cmd: gpg
    args:
      - "--batch"
      - "-u"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

brews:
  - name: flexroster
    repository:
      owner: biohackerellie
      name: homebrew-tap
      token: "{{ .Env.TAPSTOKEN }}"
    commit_author:
      name: biohackerellie
      email: epkerns@gmail.com
    homepage: "https://github.com/biohackerellie/FlexRoster"
    description: "A cli tool to manage your FlexRoster instance"
    install: |
      bin.install "flexroster"
    post_install: |
      etc.install "config.yaml" => "flexroster/config.yaml"
    test: |
      system "#{bin}/flexroster version"


checksum: 
  name_template: "checksums.txt"

source:
  enabled: true

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

# winget:
#   name: "FlexRoster"
#   publisher: "Ellie Kerns"
#   short_description: "Self hosted school scheduling software"
#   license: "GNU GPL v3"
#   publisher_url: https://epklabs.com
#   publisher_support_url: "https://github.com/biohackerellie/FlexRoster/issues"
#   package_identifier: "biohackerellie.flexroster"

#   commit_author:
#     name: "Ellie Kerns"
#     email: "epkerns@gmail.com"
#   homepage: "https://epklabs.com"
#   copyright: "Ellie Kerns"
#   release_notes: "{{.Changelog}}"
#   tags:
#     - golang
#     - school
#     - scheduling
#     - software
#     - cli
#     - flexroster

