# .github/workflows/release.yml
name: Release

on:
  push:
    branches: [main]
    tags: ["v*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.ref != 'refs/heads/main'}}

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Verify conditions
        run: |
          if [[ "${{ github.ref }}" != "refs/heads/main" || ! ${{github.actor}} == 'biohackerellie'; then
            echo "This workflow can only run on tagged commits in the main branch."
            exit 1
          fi

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      # More assembly might be required: Docker logins, GPG, etc.
      # It all depends on your needs.
      - name: Tidy Go Modules
        run: go mod tidy
        working-directory: ./cli/
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: ${{ env.GITHUB_REF_NAME }}
          args: release --clean
          workdir: "./cli/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
