# .github/workflows/release.yml
name: Release

on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.ref != 'refs/heads/main'}}

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.actor == 'biohackerellie'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      # More assembly might be required: Docker logins, GPG, etc.
      # It all depends on your needs.
      - name: Tidy Go Modules
        run: go mod tidy
        working-directory: ./cli/
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: ${{ env.GITHUB_REF_NAME }}
          args: release --clean
          workdir: "./cli/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
