-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations

-- DO $$ BEGIN
--  CREATE TYPE "Role" AS ENUM('secretary', 'teacher', 'student', 'admin');
-- EXCEPTION
--  WHEN duplicate_object THEN null;
-- END $$;
-- --> statement-breakpoint
-- CREATE TABLE IF NOT EXISTS "classRosters" (
-- 	"studentEmail" text NOT NULL,
-- 	"classroomId" text NOT NULL,
-- 	"id" serial PRIMARY KEY NOT NULL
-- );
-- --> statement-breakpoint
-- CREATE TABLE IF NOT EXISTS "transferLogs" (
-- 	"id" serial PRIMARY KEY NOT NULL,
-- 	"studentEmail" text NOT NULL,
-- 	"createdAt" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
-- 	"roomNumber" text NOT NULL,
-- 	"teacherName" text NOT NULL
-- );
-- --> statement-breakpoint
-- CREATE TABLE IF NOT EXISTS "_prisma_migrations" (
-- 	"id" varchar(36) PRIMARY KEY NOT NULL,
-- 	"checksum" varchar(64) NOT NULL,
-- 	"finished_at" timestamp with time zone,
-- 	"migration_name" varchar(255) NOT NULL,
-- 	"logs" text,
-- 	"rolled_back_at" timestamp with time zone,
-- 	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
-- 	"applied_steps_count" integer DEFAULT 0 NOT NULL
-- );
-- --> statement-breakpoint
-- CREATE TABLE IF NOT EXISTS "classrooms" (
-- 	"id" text PRIMARY KEY NOT NULL,
-- 	"roomNumber" text NOT NULL,
-- 	"teacherName" text NOT NULL,
-- 	"available" boolean DEFAULT true NOT NULL
-- );
-- --> statement-breakpoint
-- DO $$ BEGIN
--  ALTER TABLE "classRosters" ADD CONSTRAINT "classRosters_classroomId_fkey" FOREIGN KEY ("classroomId") REFERENCES "public"."classrooms"("id") ON DELETE cascade ON UPDATE cascade;
-- EXCEPTION
--  WHEN duplicate_object THEN null;
-- END $$;

